import { defineCollection, z } from 'astro:content';

const profile = defineCollection({
  type: 'content',
  schema: z.object({
    name: z.string(),
    role: z.string(),
    location: z.string(),
    email: z.string(),
    linkedinUrl: z.string().optional(),
    tagline: z.string(),
    shortBio: z.string(),
    availability: z.string(),
    navWorkLabel: z.string().default('Trabajos'),
    navProfileLabel: z.string().default('Perfil'),
    navContactLabel: z.string().default('Contacto'),
    headerStatusLabel: z.string().default('REC · Disponible'),
    heroEyebrow: z.string().default('Contenido digital · Edición para RRSS · 9:16 / 16:9'),
    heroStats: z.array(z.object({
      value: z.string(),
      label: z.string(),
    })).default([]),
    primaryCtaLabel: z.string().default('Ver trabajos'),
    secondaryCtaLabel: z.string().default('Contacto'),
    monitorStatusVideo: z.string().default('REC'),
    monitorStatusImage: z.string().default('FRAME'),
    monitorFallback: z.string().default('Selected work'),
    monitorBottomLeft: z.string().default('Vertical-first'),
    monitorFpsLabel: z.string().default('60 fps'),
    monitorFrameRate: z.coerce.number().default(60),
    marqueeItems: z.array(z.string()).default([]),
    workEyebrow: z.string().default('Trabajos seleccionados'),
    workTitle: z.string().default('El trabajo habla en movimiento.'),
    workBlockLabel: z.string().default('Bloque de trabajo'),
    workVerticalLabel: z.string().default('Reels verticales'),
    workHorizontalLabel: z.string().default('Video horizontal'),
    aboutEyebrow: z.string().default('Perfil'),
    aboutBio: z.string().default(''),
    aboutCards: z.array(z.object({
      number: z.string(),
      title: z.string(),
      text: z.string(),
    })).default([]),
    timelineEyebrow: z.string().default('Trayectoria'),
    timelineTitle: z.string().default('Experiencia reciente.'),
    timelineItems: z.array(z.object({
      date: z.string(),
      title: z.string(),
      text: z.string(),
    })).default([]),
    contactEyebrow: z.string().default('Contacto'),
    linkedinLabel: z.string().default('LinkedIn ↗'),
    emailCtaLabel: z.string().default('Escribir ↗'),
    footerNote: z.string().default('Editado con criterio'),
    projectBackLabel: z.string().default('Volver a trabajos'),
    projectClientLabel: z.string().default('Cliente'),
    projectRoleLabel: z.string().default('Rol'),
    projectFormatLabel: z.string().default('Formato'),
    projectNoMediaLabel: z.string().default('Sin medio publicado'),
    projectGalleryEyebrow: z.string().default('Piezas del trabajo'),
    projectGalleryTitle: z.string().default('Más vídeos del proyecto.'),
    projectServicesLabel: z.string().default('Servicios'),
    projectCreditsLabel: z.string().default('Créditos'),
    highlights: z.array(z.string()).default([]),
    tools: z.array(z.string()).default([]),
  }),
});

const workSections = defineCollection({
  type: 'content',
  schema: z.object({
    id: z.string(),
    title: z.string(),
    order: z.coerce.number().default(10),
    summary: z.string().optional(),
    published: z.boolean().default(true),
  }),
});

const projects = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    client: z.string(),
    year: z.coerce.number(),
    role: z.string(),
    category: z.string(),
    format: z.string(),
    summary: z.string(),
    workSection: z.string().default('codigo-nuevo'),
    workSectionOrder: z.coerce.number().optional(),
    workSectionSummary: z.string().optional(),
    thumbnail: z.string().optional(),
    videoUrl: z.string().optional(),
    videoGallery: z.array(z.object({
      title: z.string().optional(),
      videoUrl: z.string(),
    })).default([]),
    featured: z.boolean().default(false),
    published: z.boolean().default(true),
    order: z.coerce.number().default(0),
    workPlacement: z.enum(['vertical', 'horizontal']).default('vertical'),
    services: z.array(z.string()).default([]),
    credits: z.array(z.string()).default([]),
  }),
});

export const collections = { profile, workSections, projects };
